#!/usr/bin/env ansible-playbook
---

- hosts: localhost
  gather_facts: False
  tags: once

  vars: &vars

    default_version: v0.1.0
    secret_dir:      ext/secret
    secret_version:  '{{ version | default(default_version) }}'
    secret:          '{{ secret_dir}}/{{ secret_version }}/vars'

  tasks:

    - git:
        repo: git@github.com:Epiconcept-Paris/infra-secret.git
        version: '{{ secret_version }}'
        dest: '{{ secret_dir}}/{{ secret_version }}'
        key_file: ~/.ssh/id_epiconcept
      when: secret_version != 'debug'
      tags: git
      name: get infra-secret

- hosts: localhost
  gather_facts: True
  tags: main

  vars: *vars

  tasks:

    - lineinfile:
        path: .gitignore
        line: '{{ item }}'
      with_items: [ vars/ext ]

    - file:
        path: '{{ playbook_dir}}/vars/ext/secret'
        state: directory

    - copy:
        src: '{{ secret }}/{{ item }}.yml'
        dest: '{{ playbook_dir}}/vars/ext/secret/{{ item }}.yml'
        mode: 0444
      with_items:
        - passwords
      name: secrets
